# Generated by Django 4.2.7 on 2023-11-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteducator',
            name='sertificate_id_numeric',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
