# Generated by Django 4.2.7 on 2024-08-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybersecurity',
            name='amal_qilish',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cybersecurity',
            name='berilgan_vaqt',
            field=models.CharField(max_length=12),
        ),
    ]
