# Generated by Django 4.2.7 on 2023-11-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_iteducator_sertificate_id_numeric'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasciense',
            name='sertificate_id_numeric',
            field=models.IntegerField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fullstack',
            name='sertificate_id_numeric',
            field=models.IntegerField(blank=True, default=2, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interiordesign',
            name='sertificate_id_numeric',
            field=models.IntegerField(blank=True, default=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='sertificate_id_numeric',
            field=models.IntegerField(blank=True, default=4, unique=True),
            preserve_default=False,
        ),
    ]
