# Generated by Django 4.2.7 on 2023-11-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_fullstack_backend_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasciense',
            name='data_science_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasciense',
            name='machina_learning_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
