# Generated by Django 4.2.7 on 2023-11-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_datasciense_data_science_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familya', models.CharField(max_length=50)),
                ('sharif', models.CharField(max_length=50)),
                ('berilgan_vaqt', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('seria', models.CharField(max_length=3)),
                ('sertificate_id', models.CharField(blank=True, max_length=7, unique=True)),
                ('sertificate_id_numeric', models.IntegerField(blank=True, unique=True)),
                ('pptx_file', models.FileField(blank=True, upload_to='pptx_other')),
                ('sertificate_front', models.FileField(upload_to='other_ser_front/')),
            ],
        ),
    ]
