# Generated by Django 4.2.7 on 2024-03-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familya', models.CharField(max_length=50)),
                ('sharif', models.CharField(max_length=50)),
                ('berilgan_vaqt', models.CharField(max_length=200)),
                ('seria', models.CharField(max_length=3)),
                ('sertificate_id', models.CharField(blank=True, max_length=7, unique=True)),
                ('sertificate_id_numeric', models.IntegerField(blank=True, unique=True)),
                ('pptx_file', models.FileField(blank=True, upload_to='pptx_cyber_security')),
                ('sertificate_front', models.FileField(blank=True, upload_to='cyber_security_front/')),
                ('qr_code', models.ImageField(blank=True, upload_to='cyber_security_qrcode/')),
            ],
        ),
    ]
