# Generated by Django 4.2.7 on 2024-03-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_cybersecurity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cybersecurity',
            name='seria',
            field=models.CharField(default='CS', max_length=3),
        ),
    ]
