# Generated by Django 4.2.7 on 2024-03-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_cybersecurity_seria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cybersecurity',
            name='sharif',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
