# Generated by Django 4.2.7 on 2024-06-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_rename_sertificate_back_iteducator_certificate_back_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interiordesign',
            old_name='sertificate_front',
            new_name='certificate_front',
        ),
        migrations.RenameField(
            model_name='interiordesign',
            old_name='sertificate_id',
            new_name='certificate_id',
        ),
        migrations.RenameField(
            model_name='interiordesign',
            old_name='sertificate_id_numeric',
            new_name='certificate_id_numeric',
        ),
        migrations.RenameField(
            model_name='interiordesign',
            old_name='familya',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='interiordesign',
            old_name='berilgan_vaqt',
            new_name='issue_date',
        ),
        migrations.RenameField(
            model_name='interiordesign',
            old_name='ism',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='interiordesign',
            old_name='sharif',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='interiordesign',
            old_name='seria',
            new_name='series',
        ),
    ]
